apiVersion: v1
kind: ConfigMap
metadata:
  name: log4j2-stdout-config
  namespace: kafka
data:
  log4j2.yaml: |
    Configuration:
      status: info
      appenders:
        stdout:
          type: Console
          name: stdout
          layout:
            type: PatternLayout
            pattern: "[%d] %p %m (%c:%L)%n"
      loggers:
        root:
          level: info
          AppenderRef:
            - ref: stdout